language: python
python:
  - 2.6
  - 2.7

# command to install dependencies
env:
  - CONFIG="pytest==2.2.3 pytest-xdist"
  - CONFIG="pytest==2.2.3"
  - CONFIG="pytest==2.2.4 pytest-xdist"
  - CONFIG="pytest==2.2.4"
  - CONFIG="pytest==2.3 pytest-xdist"
  - CONFIG="pytest==2.3"
  - CONFIG="pytest==2.3.1 pytest-xdist"
  - CONFIG="pytest==2.3.1"
  - CONFIG="pytest==2.3.2 pytest-xdist"
  - CONFIG="pytest==2.3.2"
  - CONFIG="pytest==2.3.3 pytest-xdist"
  - CONFIG="pytest==2.3.3"
  - CONFIG="pytest==2.3.4 pytest-xdist"
  - CONFIG="pytest==2.3.4"
  - CONFIG="pytest pytest-xdist"
  - CONFIG="pytest --use-mirrors"

install: 
  - pip install --use-mirrors $CONFIG
  - "python setup.py install"

# command to run tests
script: "py.test ."

notifications:
  email:
    - dave.hunt@gmail.com
  irc:
    - "irc.mozilla.org#automation"
