from setuptools import setup

setup(name='pytest-moztrap',
      version='0.2',
      description='MozTrap plugin for py.test.',
      author='Leah Klearman',
      author_email='lklrmn@gmail.com',
      url='https://github.com/klrmn/pytest-moztrap',
      py_modules=['pytest_moztrap', 'connect_results'],
      install_requires=['pytest>=2.2.3'],
      entry_points={'pytest11': ['pytest_moztrap = pytest_moztrap']},
      license='Mozilla Public License 2.0 (MPL 2.0)',
      keywords='py.test pytest moztrap test management mozilla',
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
                   'Operating System :: POSIX',
                   'Operating System :: Microsoft :: Windows',
                   'Operating System :: MacOS :: MacOS X',
                   'Topic :: Software Development :: Quality Assurance',
                   'Topic :: Software Development :: Testing',
                   'Topic :: Utilities',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 2.6',
                   'Programming Language :: Python :: 2.7'])
